#!/usr/bin/env node
// Build the standalone WebUI and embed the exact hashed assets in the Rust distribution.
import {
  readdirSync,
  readFileSync,
  writeFileSync,
  mkdirSync,
  rmSync,
  existsSync,
} from "node:fs";
import { join, dirname, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
const root = join(dirname(fileURLToPath(import.meta.url)), ".."),
  ui = join(root, "ui"),
  out = join(root, "cli/ui");
const check = process.argv.includes("--check");
if (!check)
  execFileSync(
    process.platform === "win32" ? "npm.cmd" : "npm",
    ["run", "build"],
    { cwd: ui, stdio: "inherit", shell: process.platform === "win32" },
  );
const distribution = join(ui, "dist");
if (!existsSync(join(distribution, "index.html")))
  throw new Error(
    "Run node scripts/build_ui.mjs before checking embedded assets",
  );
const files = [];
function walk(directory) {
  for (const name of readdirSync(directory, { withFileTypes: true })) {
    const path = join(directory, name.name);
    if (name.isDirectory()) walk(path);
    else
      files.push({
        path: relative(distribution, path).replaceAll("\\", "/"),
        bytes: readFileSync(path),
      });
  }
}
walk(distribution);
const mime = (path) =>
  path.endsWith(".js")
    ? "text/javascript; charset=utf-8"
    : path.endsWith(".css")
      ? "text/css; charset=utf-8"
      : path.endsWith(".svg")
        ? "image/svg+xml"
        : "application/octet-stream";
const assets = files
  .filter((f) => f.path !== "index.html")
  .sort((a, b) => a.path.localeCompare(b.path));
const rust =
  "// Generated by scripts/build_ui.mjs. Do not edit.\npub const FILES: &[(&str, &str, &[u8])] = &[\n" +
  assets
    .map(
      (f) =>
        "    (" +
        JSON.stringify("/" + f.path) +
        ", " +
        JSON.stringify(mime(f.path)) +
        ", include_bytes!(" +
        JSON.stringify(f.path) +
        ")),",
    )
    .join("\n") +
  "\n];\n";
const fingerprint = createHash("sha256");
for (const path of [
  "package.json",
  "package-lock.json",
  "tsconfig.json",
  "vite.config.ts",
  "index.html",
])
  fingerprint.update(readFileSync(join(ui, path)));
function sourceHash(directory) {
  for (const entry of readdirSync(directory, { withFileTypes: true }).sort(
    (a, b) => a.name.localeCompare(b.name),
  )) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) sourceHash(path);
    else if (
      /\.(ts|tsx|css|svg|png|ico)$/.test(entry.name) &&
      !entry.name.includes(".test.")
    ) {
      fingerprint.update(relative(ui, path));
      fingerprint.update(readFileSync(path));
    }
  }
}
sourceHash(join(ui, "src"));
if (existsSync(join(ui, "public"))) sourceHash(join(ui, "public"));
const hash = fingerprint.digest("hex") + "\n";
if (check) {
  if (readFileSync(join(out, "source.sha256"), "utf8") !== hash)
    throw new Error(
      "WebUI sources changed: rebuild with node scripts/build_ui.mjs",
    );
  if (readFileSync(join(out, "assets.rs"), "utf8") !== rust)
    throw new Error("Embedded asset registry is stale");
  for (const file of files) {
    const target = join(out, file.path);
    if (!existsSync(target) || !readFileSync(target).equals(file.bytes))
      throw new Error("Stale embedded asset: " + file.path);
  }
} else {
  mkdirSync(out, { recursive: true });
  rmSync(join(out, "assets"), { recursive: true, force: true });
  for (const file of files) {
    mkdirSync(dirname(join(out, file.path)), { recursive: true });
    writeFileSync(join(out, file.path), file.bytes);
  }
  writeFileSync(join(out, "assets.rs"), rust);
  writeFileSync(join(out, "source.sha256"), hash);
}
console.log(
  "PASS: standalone WebUI and embedded assets match (" +
    files.length +
    " files)",
);
