// Generated by scripts/build_ui.mjs. Do not edit.
pub const FILES: &[(&str, &str, &[u8])] = &[
    ("/assets/editor-J9SU0uel.js", "text/javascript; charset=utf-8", include_bytes!("assets/editor-J9SU0uel.js")),
    ("/assets/index-4lGY7dmH.js", "text/javascript; charset=utf-8", include_bytes!("assets/index-4lGY7dmH.js")),
    ("/assets/index-DE6S8qL8.css", "text/css; charset=utf-8", include_bytes!("assets/index-DE6S8qL8.css")),
    ("/assets/NcViews-Cqf_HhHO.js", "text/javascript; charset=utf-8", include_bytes!("assets/NcViews-Cqf_HhHO.js")),
    ("/assets/react-dgengZBm.js", "text/javascript; charset=utf-8", include_bytes!("assets/react-dgengZBm.js")),
    ("/favicon.svg", "image/svg+xml", include_bytes!("favicon.svg")),
];
